### ISSUE TITLE
Improved interpretation (and/or warning for) bis(2-hydroxyethyl)oleylamine

### ISSUE THREAD

**Issue by rogersayle** [dan2097/opsin#165] opened 2021-11-24 14:36 UTC
Hi Daniel,
The folks at the NCBI have reported some feedback that the structure of https://pubchem.ncbi.nlm.nih.gov/substance/224856400 may be incorrect.  Naturally with implicit locants "bis(2-hydroxyethyl)oleylamine" should probably be reporting an APPEARS_AMBIGUOUS warning from OPSIN, but the choice of the implicit locant on "oleylamine" is unusual; Compare "bis(ethyl)hexylamine" which places the ethyl groups on the nitrogen, to "bis(ethyl)oleylamine", which suspiciously extends alkyl groups with alkyl groups [note OPSIN's interpretation for bis(chloro)oleylamine" is not unreasonable].  Is this easy to tweak?
Thanks in advance,
Roger

**Comment by dan2097** [comment] 2021-11-25 01:32
Generalizing the alkyl support to include traditional acids is definitely possible. The fix I'm testing also changes the interpretation of things like Benzylpropynoylamine to Benzyl(propynoyl)amine, which emprically does seem to be the more often intended interpretation. (benzyl being the yl form of benzoic acid)
Duplicate of #164

**Closed by dan2097** 2021-11-25 01:32 UTC
